In [2]:
# 
# 
# M3 Challenge: Modeling the Future
# 
# Code to compile raw Louisiana and California Weather, Crop Growth, Crop Damage, and Insurance data
# from 01/2000 to 12/2020
# 
# 

#NOAA Merge
import pandas as pd
import io
import numpy as np

testFile = '' #LATest.xlsx or CATest.xlsx files
copyFile = '' #LACopy.xlsx or CACopy.xlsx files
finalFile = '' #FinalLA.xlsx or FinalCA.xlsx files


df2 = pd.read_excel(testFile)
df3 = pd.read_excel(copyFile)

allTitles = ['PalmerZIndex',	'PalmerZIndexAnomaly',	'AverageTemp',	'AverageTempAnomaly',	'CoolingDays',	'CoolingDaysAnomaly',	'HeatingDays',	'HeatingDaysAnomaly',	'PalmerDroughtSeverityIndex',	'PalmerDroughtSeverityIndexAnomaly',	'PalmerHydrologicalDroughtIndex', 'PalmerHydrologicalDroughtIndexAnomaly', 'PalmerModifiedDroughtIndex', 'PalmerModifiedDroughtIndexAnomaly', 'Precipitation', 'PrecipitationAnomaly']
allYms = [200001, 200002, 200003, 200004, 200005, 200006, 200007, 200008, 200009, 200010, 200011, 200012, 200101, 200102, 200103, 200104, 200105, 200106, 200107, 200108, 200109, 200110, 200111, 200112, 200201, 200202, 200203, 200204, 200205, 200206, 200207, 200208, 200209, 200210, 200211, 200212, 200301, 200302, 200303, 200304, 200305, 200306, 200307, 200308, 200309, 200310, 200311, 200312, 200401, 200402, 200403, 200404, 200405, 200406, 200407, 200408, 200409, 200410, 200411, 200412, 200501, 200502, 200503, 200504, 200505, 200506, 200507, 200508, 200509, 200510, 200511, 200512, 200601, 200602, 200603, 200604, 200605, 200606, 200607, 200608, 200609, 200610, 200611, 200612, 200701, 200702, 200703, 200704, 200705, 200706, 200707, 200708, 200709, 200710, 200711, 200712, 200801, 200802, 200803, 200804, 200805, 200806, 200807, 200808, 200809, 200810, 200811, 200812, 200901, 200902, 200903, 200904, 200905, 200906, 200907, 200908, 200909, 200910, 200911, 200912, 201001, 201002, 201003, 201004, 201005, 201006, 201007, 201008, 201009, 201010, 201011, 201012, 201101, 201102, 201103, 201104, 201105, 201106, 201107, 201108, 201109, 201110, 201111, 201112, 201201, 201202, 201203, 201204, 201205, 201206, 201207, 201208, 201209, 201210, 201211, 201212, 201301, 201302, 201303, 201304, 201305, 201306, 201307, 201308, 201309, 201310, 201311, 201312, 201401, 201402, 201403, 201404, 201405, 201406, 201407, 201408, 201409, 201410, 201411, 201412, 201501, 201502, 201503, 201504, 201505, 201506, 201507, 201508, 201509, 201510, 201511, 201512, 201601, 201602, 201603, 201604, 201605, 201606, 201607, 201608, 201609, 201610, 201611, 201612, 201701, 201702, 201703, 201704, 201705, 201706, 201707, 201708, 201709, 201710, 201711, 201712, 201801, 201802, 201803, 201804, 201805, 201806, 201807, 201808, 201809, 201810, 201811, 201812, 201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002]

for title in allTitles:
  df2[title] = np.nan

for index, row in df2.iterrows():
  for indexO, rowO in df3.iterrows():
    if(int(rowO['Date']) == int(row['ym'])):
      for title in allTitles:
        df2.loc[index, title] = rowO[title]

df2.to_excel(finalFile)

FileNotFoundError: [Errno 2] No such file or directory: ''

In [ ]:
##LOUISIANA CODE
import pandas as pd
import io
import numpy as np

rawFile = '' #LARaw.xlsx

df = pd.read_excel(rawFile)

df1 = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

df2 = df1.sort_values([4,6,'ym'])
df2 = df2.reset_index(drop=True)




########################

allCounties = ['Acadia', 'Allen', 'Avoyelles', 'Bossier', 'Caddo', 'Calcasieu', 'Caldwell', 'Cameron', 'Catahoula', 'Concordia', 'East Carroll', 'Evangeline', 'Franklin', 'Grant', 'Iberia', 'Jefferson Davis', 'Lafayette', 'Madison', 'Morehouse', 'Natchitoches', 'Ouachita', 'Pointe Coupee', 'Rapides', 'Red River', 'Richland', 'St Landry', 'St Martin', 'Tensas', 'Vermilion', 'West Carroll']
allYms = [200001, 200002, 200003, 200004, 200005, 200006, 200007, 200008, 200009, 200010, 200011, 200012, 200101, 200102, 200103, 200104, 200105, 200106, 200107, 200108, 200109, 200110, 200111, 200112, 200201, 200202, 200203, 200204, 200205, 200206, 200207, 200208, 200209, 200210, 200211, 200212, 200301, 200302, 200303, 200304, 200305, 200306, 200307, 200308, 200309, 200310, 200311, 200312, 200401, 200402, 200403, 200404, 200405, 200406, 200407, 200408, 200409, 200410, 200411, 200412, 200501, 200502, 200503, 200504, 200505, 200506, 200507, 200508, 200509, 200510, 200511, 200512, 200601, 200602, 200603, 200604, 200605, 200606, 200607, 200608, 200609, 200610, 200611, 200612, 200701, 200702, 200703, 200704, 200705, 200706, 200707, 200708, 200709, 200710, 200711, 200712, 200801, 200802, 200803, 200804, 200805, 200806, 200807, 200808, 200809, 200810, 200811, 200812, 200901, 200902, 200903, 200904, 200905, 200906, 200907, 200908, 200909, 200910, 200911, 200912, 201001, 201002, 201003, 201004, 201005, 201006, 201007, 201008, 201009, 201010, 201011, 201012, 201101, 201102, 201103, 201104, 201105, 201106, 201107, 201108, 201109, 201110, 201111, 201112, 201201, 201202, 201203, 201204, 201205, 201206, 201207, 201208, 201209, 201210, 201211, 201212, 201301, 201302, 201303, 201304, 201305, 201306, 201307, 201308, 201309, 201310, 201311, 201312, 201401, 201402, 201403, 201404, 201405, 201406, 201407, 201408, 201409, 201410, 201411, 201412, 201501, 201502, 201503, 201504, 201505, 201506, 201507, 201508, 201509, 201510, 201511, 201512, 201601, 201602, 201603, 201604, 201605, 201606, 201607, 201608, 201609, 201610, 201611, 201612, 201701, 201702, 201703, 201704, 201705, 201706, 201707, 201708, 201709, 201710, 201711, 201712, 201801, 201802, 201803, 201804, 201805, 201806, 201807, 201808, 201809, 201810, 201811, 201812, 201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002]
allCrops = ['RICE', 'COTTON']
countyCodes = [1, 3, 9, 15, 17, 19, 21, 23, 25, 29, 35, 39, 41, 43, 45, 53, 55, 65, 67, 69, 73, 77, 79, 81, 83, 97, 99, 107, 113, 123]
cropCodes = [18, 21]

for coName in allCounties:
  for cr in allCrops:
    ymList = []
    for index, row in df2.iterrows():
      if (row[4] == coName and row[6] == cr):
        ymList.append(row['ym'])
    for yeMo in allYms:
      if (yeMo not in ymList):
        #df2 = df2.append(pd.DataFrame([[yeMo, int(str(yeMo)[:4]), 6, 'CA', 0, coName, 0, cr, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], columns =df2.columns))
        df2 = df2.append(pd.DataFrame([[yeMo, int(str(yeMo)[:4]), 22, 'LA', countyCodes[allCounties.index(coName)], coName, cropCodes[allCrops.index(cr)], cr, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, int(str(yeMo)[-2:]), np.nan, np.nan, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], columns =df2.columns))
    
    # first nan = county code
    # second nan = crop code
    # rest are = i, j, k, l, m, n etc.
df2 = df2.sort_values([4,6,'ym'])
df2 = df2.reset_index(drop=True)

df2.to_excel(testFile)

In [ ]:
##CALIFORNIA CODE
import pandas as pd
import io
import numpy as np

rawFile = '' #CARaw.xlsx

df = pd.read_excel(rawFile)

df1 = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

df2 = df1.sort_values([4,6,'ym'])
df2 = df2.reset_index(drop=True)

########################

allCounties = ['Butte', 'Colusa', 'Fresno', 'Glenn', 'Imperial', 'Kern', 'Kings', 'Madera', 'Merced', 'Placer', 'Riverside', 'Sacramento', 'San Joaquin', 'Stanislaus', 'Sutter', 'Tehama', 'Tulare', 'Yolo', 'Yuba']
allYms = [200001, 200002, 200003, 200004, 200005, 200006, 200007, 200008, 200009, 200010, 200011, 200012, 200101, 200102, 200103, 200104, 200105, 200106, 200107, 200108, 200109, 200110, 200111, 200112, 200201, 200202, 200203, 200204, 200205, 200206, 200207, 200208, 200209, 200210, 200211, 200212, 200301, 200302, 200303, 200304, 200305, 200306, 200307, 200308, 200309, 200310, 200311, 200312, 200401, 200402, 200403, 200404, 200405, 200406, 200407, 200408, 200409, 200410, 200411, 200412, 200501, 200502, 200503, 200504, 200505, 200506, 200507, 200508, 200509, 200510, 200511, 200512, 200601, 200602, 200603, 200604, 200605, 200606, 200607, 200608, 200609, 200610, 200611, 200612, 200701, 200702, 200703, 200704, 200705, 200706, 200707, 200708, 200709, 200710, 200711, 200712, 200801, 200802, 200803, 200804, 200805, 200806, 200807, 200808, 200809, 200810, 200811, 200812, 200901, 200902, 200903, 200904, 200905, 200906, 200907, 200908, 200909, 200910, 200911, 200912, 201001, 201002, 201003, 201004, 201005, 201006, 201007, 201008, 201009, 201010, 201011, 201012, 201101, 201102, 201103, 201104, 201105, 201106, 201107, 201108, 201109, 201110, 201111, 201112, 201201, 201202, 201203, 201204, 201205, 201206, 201207, 201208, 201209, 201210, 201211, 201212, 201301, 201302, 201303, 201304, 201305, 201306, 201307, 201308, 201309, 201310, 201311, 201312, 201401, 201402, 201403, 201404, 201405, 201406, 201407, 201408, 201409, 201410, 201411, 201412, 201501, 201502, 201503, 201504, 201505, 201506, 201507, 201508, 201509, 201510, 201511, 201512, 201601, 201602, 201603, 201604, 201605, 201606, 201607, 201608, 201609, 201610, 201611, 201612, 201701, 201702, 201703, 201704, 201705, 201706, 201707, 201708, 201709, 201710, 201711, 201712, 201801, 201802, 201803, 201804, 201805, 201806, 201807, 201808, 201809, 201810, 201811, 201812, 201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002]
allCrops = ['RICE', 'COTTON', 'COTTON EX LONG STAPLE']
countyCodes = [7, 11, 19, 21, 25, 29, 31, 39, 47, 61, 65, 67, 77, 99, 101, 103, 107, 113, 115]
cropCodes = [18, 21, 22]

for coName in allCounties:
  for cr in allCrops:
    ymList = []
    for index, row in df2.iterrows():
      if (row[4] == coName and row[6] == cr):
        ymList.append(row['ym'])
    for yeMo in allYms:
      if (yeMo not in ymList):
        #df2 = df2.append(pd.DataFrame([[yeMo, int(str(yeMo)[:4]), 6, 'CA', 0, coName, 0, cr, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], columns =df2.columns))
        df2 = df2.append(pd.DataFrame([[yeMo, int(str(yeMo)[:4]), 6, 'CA', countyCodes[allCounties.index(coName)], coName, cropCodes[allCrops.index(cr)], cr, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, int(str(yeMo)[-2:]), np.nan, np.nan, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], columns =df2.columns))
    
    # first nan = county code
    # second nan = crop code
    # rest are = i, j, k, l, m, n etc.
df2 = df2.sort_values([4,6,'ym'])
df2 = df2.reset_index(drop=True)

df2.to_excel(testFile)

In [ ]:
## Sample Code
##
import pandas as pd
import io
import numpy as np

df = pd.read_excel('test.xlsx')


#df1 = df.drop_duplicates(subset=['ym','county','crop'], keep="first").sort_values('ym')
df2 = df.sort_values(['county','ym'])
df2 = df2.reset_index(drop=True)

allCounties = ['Colusa', 'Fresno']
allYms = [200001, 200002, 200003, 200004, 200005, 200006, 200007, 200008, 200009, 200010, 200011, 200012]
allCrops = ['RICE','COTTON']

for coName in allCounties:
  for cr in allCrops:
    ymList = []
    for index, row in df2.iterrows():
      print(row['county'] == coName and row['crop'] == cr)
      if (row['county'] == coName and row['crop'] == cr):
        ymList.append(row['ym'])
        print(row['ym'])
    for yeMo in allYms:
      if (yeMo not in ymList):
        df2 = df2.append(pd.DataFrame([[yeMo,'CA',coName, cr, 0]], columns =df2.columns))

#####for coName in allCounties:
  #####ymList = []
  #####for index, row in df2.iterrows():
    #####if (row['county'] == coName):
      #####ymList.append(row['ym'])
  #####for yeMo in allYms:
    #####if (yeMo not in ymList):
      #####df2 = df2.append(pd.DataFrame([[yeMo,'CA',coName, 'COTTON', 0]], columns =df2.columns))
  
df2 = df2.sort_values(['county','ym'])
df2 = df2.reset_index(drop=True)

df2.to_excel('test1.xlsx')
#df1.set_index("ym")
#new_index = [200006, 200007, 200008, 200009, 200010, 200011, 200012]#pd.Index(np.arange(0,7,1), name="ym")
#df1.set_index("ym").reindex(new_index, fill_value=0)
##print (df1)

False
False
False
True
200006
False
False
False
False
False
False
False
True
200004
True
200005
True
200005
False
True
200009
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
200004
False
True
200004
False
False
True
200012
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
200004
False
True
200010
True
200010
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False

In [ ]:
# Returns lists of combined years and months for new xlsx date column
#

years = ['2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020']
months = ['01','02','03','04','05','06','07','08','09','10','11','12']

finList = []

for y in years:
  for m in months:
    finList.append(int(y+m))

print(finList)

[200001, 200002, 200003, 200004, 200005, 200006, 200007, 200008, 200009, 200010, 200011, 200012, 200101, 200102, 200103, 200104, 200105, 200106, 200107, 200108, 200109, 200110, 200111, 200112, 200201, 200202, 200203, 200204, 200205, 200206, 200207, 200208, 200209, 200210, 200211, 200212, 200301, 200302, 200303, 200304, 200305, 200306, 200307, 200308, 200309, 200310, 200311, 200312, 200401, 200402, 200403, 200404, 200405, 200406, 200407, 200408, 200409, 200410, 200411, 200412, 200501, 200502, 200503, 200504, 200505, 200506, 200507, 200508, 200509, 200510, 200511, 200512, 200601, 200602, 200603, 200604, 200605, 200606, 200607, 200608, 200609, 200610, 200611, 200612, 200701, 200702, 200703, 200704, 200705, 200706, 200707, 200708, 200709, 200710, 200711, 200712, 200801, 200802, 200803, 200804, 200805, 200806, 200807, 200808, 200809, 200810, 200811, 200812, 200901, 200902, 200903, 200904, 200905, 200906, 200907, 200908, 200909, 200910, 200911, 200912, 201001, 201002, 201003, 201004, 201005, 201006, 201007, 201008, 201009, 201010, 201011, 201012, 201101, 201102, 201103, 201104, 201105, 201106, 201107, 201108, 201109, 201110, 201111, 201112, 201201, 201202, 201203, 201204, 201205, 201206, 201207, 201208, 201209, 201210, 201211, 201212, 201301, 201302, 201303, 201304, 201305, 201306, 201307, 201308, 201309, 201310, 201311, 201312, 201401, 201402, 201403, 201404, 201405, 201406, 201407, 201408, 201409, 201410, 201411, 201412, 201501, 201502, 201503, 201504, 201505, 201506, 201507, 201508, 201509, 201510, 201511, 201512, 201601, 201602, 201603, 201604, 201605, 201606, 201607, 201608, 201609, 201610, 201611, 201612, 201701, 201702, 201703, 201704, 201705, 201706, 201707, 201708, 201709, 201710, 201711, 201712, 201801, 201802, 201803, 201804, 201805, 201806, 201807, 201808, 201809, 201810, 201811, 201812, 201901, 201902, 201903, 201904, 201905, 201906, 201907, 201908, 201909, 201910, 201911, 201912, 202001, 202002, 202003, 202004, 202005, 202006, 202007, 202008, 202009, 202010, 202011, 202012]